### ISSUE TITLE
WeDo Robot Configuration Missing Lable

### ISSUE THREAD

**Issue by Thorlogy** [OpenRoberta/robertalab#959]
In the RobotConfiguration two lables are missing:
![image](https://user-images.githubusercontent.com/19221359/42924177-379cfc18-8b29-11e8-8946-3bbfddc6e915.png)

I would recommend to name this 

English: "Connector" 
German: "Anschluss" 

It should not called "Port" because thats the lable for the actors and sensors:
![image](https://user-images.githubusercontent.com/19221359/42924301-dae80368-8b29-11e8-88b4-39a04de7d667.png)

**Comment by Thorlogy** [comment]
Additional note: The lable which belongs to wedo should called "Hub"

**Comment by bjost2s** [comment]
this was already fixed in hotfix2.8.1 before you created this issue. Please close

**Comment by Thorlogy** [comment]
Sorry the issue still exist

![image](https://user-images.githubusercontent.com/19221359/43075947-bcaf438c-8e82-11e8-8ded-5b31ec5fb662.png)
